### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by Dhaiven**

### CODE REVIEW

**Comment by smartcmd** [comment]
LGTM

**Comment by smartcmd** [comment]
Have you updated the protocol library?
I can't see the change

**Comment by IWareQ** [comment]
I think it requires updating the `Data` files

**Comment by smartcmd** [comment]
> I think it requires updating the `Data` files

Agree, we should wait for endstone to update

**Comment by IWareQ** [comment]
> > I think it requires updating the `Data` files
> 
> 
> 
> Agree, we should wait for endstone to update

Endstone already supported 1.21.3

**Comment by smartcmd** [comment]
> > > I think it requires updating the `Data` files
> > 
> > 
> > Agree, we should wait for endstone to update
> 
> Endstone already supported 1.21.3

I know but....1.21.3 doesn't have protocol change. I think he means 1.21.20

**Comment by smartcmd** [comment]
BTW we should also update `ProtocolInfo` class

**Review by IWareQ — COMMENTED** [review]
1. Update `ProtocolInfo` class
2. Update `Data` files. Get from Endstone

**Pull request merged**
